[main]
token = "YOUR_TOKEN"

[channel]
insert_position = 2
min_channels = 1
role_prefix = 'Channel: '
names = ["First", "Second"]

[command]
prefix = '!'
history_length = 32

[log]
channel = "CHANNEL_coID"
